#!/usr/bin/env bash
# File that helps to transfer a file
# from a client to a server

if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	if [ $# -eq 3 ]; then
		scp -o StrictHostKeyCheck=no "$1" "$3@$2:~/"
	elif [ $# -eq 4 ]; then
		scp -o StrictHostKeyCheck=no -i "$4" "$1" "$3@$2:~/"
	fi
fi
