#!/usr/bin/env bash
# This script creates a file
# It also deletes the file on SIGQUIT or SIGTERM

behead() {
	sudo rm /var/run/myscript.pid
	exit
}

sudo touch /var/run/myscript.pid && echo "$$" > /var/run/myscript.pid

while true
do
	echo "To infinity and beyound"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && behead' SIGTERM
	trap 'behead' SIGQUIT
done
