#!/usr/bin/env bash
#This script uses case and while to display ouput 

val=1
while [ $val -le 20 ]
do
	case $val in 
		5) echo "bad luck from China";;
		10) echo "bad luck from Japan";;
		18) echo "bad luck from Italy";;
	esac
	echo "$val"	
	((val=val+1))
done
