#!/usr/bin/env bash
# Script to change localhost and block facebook
cp /etc/hosts hosts_cp
echo "8.8.8.8	facebook.com" >> hosts_cp
grep -rl "127.0.0.1" hosts_cp | xargs sed -i 's/127.0.0.1/127.0.0.2/g'
cp hosts_cp /etc/hosts
